name: 主任务

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:

  # 构建ShiauweiZhao/Photonix项目（单个Dockerfile在根目录）
  build-photonix:
    uses: ./.github/workflows/build.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      source_repo: 'ShiauweiZhao/Photonix'
      docker_image_name: 'photonix'

  # 使用docker-compose构建BiliNote项目（推荐方式）
  build-bili-note-with-compose:
    uses: ./.github/workflows/build.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      source_repo: 'JefferyHcool/BiliNote'
      docker_image_name: 'bili-note'
      use_compose_build: true
      compose_file_path: 'docker-compose.yml'
      additional_files_to_copy: '[{"source": ".env.example", "destination": ".env"}]'
    
  # 构建Minerchu/dongguaTV项目（单个Dockerfile在根目录）
  build-dongguaTV:
    uses: ./.github/workflows/build.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      source_repo: 'Minerchu/dongguaTV'
      docker_image_name: 'donggua-tv'
      
  # 构建Minerchu/dongguaTV项目（单个Dockerfile在根目录）
  build-ogame-vue-ts:
    uses: ./.github/workflows/build.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      source_repo: 'setube/ogame-vue-ts'
      docker_image_name: 'ogame-vue-ts'
      
      
  # 清除旧的workflow运行记录
  cleanup-workflow-runs:
    runs-on: ubuntu-latest
    steps:
      - name: 删除旧 Actions
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.CLEANUP_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 2
